sudo: required
services:
  - docker

before_install:
  - docker build -t miguelmartinez11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true miguelmartinez11/react-test npm test -- --coverage

after_success:
  - docker build -t miguelmartinez11/bookaway-client ./client
  - docker build -t miguelmartinez11/bookaway-nginx ./nginx
  - docker build -t miguelmartinez11/bookaway-server .

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push miguelmartinez11/bookaway-client
  - docker push miguelmartinez11/bookaway-nginx
  - docker push miguelmartinez11/bookaway-server

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: bookaway
  env: Bookaway-env
  bucket_name: elasticbeanstalk-eu-west-1-700002782697
  bucket_path: bookaway-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY